# This properties file is used to create a PropertyResourceBundle
# It contains Locale specific strings used in the project.
#
# @author Yudalang

#################################
###  UniSoft Infrastructure  ###
#################################

lookAndFeel.text = Look and Feel
sourceCodeCheckboxItem.text = Show Source Code

general.button.import=Import
general.button.export=Export
general.button.cancel=Cancel
general.button.applyAndClose=Apply and close

features.not.implement=Sorry, the feature has not implement yet.\nPlease contact the developments.
features.not.implement2=<ul><li>Sorry, not implemented.</li><li>The author may not have time to accomplish it</li><li>Or this information is useless.</li>

## The preference settings
Pref.font.tooltip = <html>Font setting takes effect after restarting the software.<br>Not if you set the "simSun" font, the size should be even number.
Pref.font.sample = The evolutionary Genotype Phenotype System Biology
Pref.font.family.name = Font Family
Pref.font.style.name = Font Style
Pref.font.size.name = Font Size
Pref.font.example.name = Example

### Preference Menu ###
Pref.action.title=Preference of the software interface.
Pref.action.name=Preference  
Pref.action.restore.name=Restore Defaults  
Pref.action.restore.tip=After restart the software to make effects.
Pref.action.relaunch.tip=Note: some settings may take effects after re-launch the software.

Pref.action.showconfig.name=Show Configuration  
Pref.action.showconfig.tip=Direct input the parameters.


### File Menu ###

FileMenu.label=File
FileMenu.tooltip=Actions to operate data and exit software
FileMenu.import.label=Import
FileMenu.import.tooltip=Import files to start.
FileMenu.export.label=Export
FileMenu.exit.label=Exit
FileMenu.exit.content=Confirm to exit ?

### MainFrame Core Menu ###

MainframeCoreMenu.label=Mainframe core
MainframeCoreMenu.tooltip=Actions to launch the core modules of the mainframe


### iTools Menu ###

IToolsMenu.label=iTools
IToolsMenu.tooltip=Independent tools to conduct data analysis  


### Options Menu ###

OptionsMenu.label=Options
OptionsMenu.tooltip=Options to adjust software

### help Menu ###

HelpMenu.label=Help
infor.Menu.label=Information
statics.Menu.label=Statistics


### Plugins Menu ###

Plugins.label=Plug-ins
Plugins.tooltip=Modules load as plug-ins

### Plugins Menu ###

Bonus.label=Bonus module
Bonus.tooltip=Modules that enabled by the rank of user


### Module

Default.introduction.module.name=Introduction
Default.introduction.module.tip=A tab to introduce representative features of software.
introduction.module.open.button=Open module
introduction.module.GrapIll.name=English document/instruction/tutorial/manual: 
introduction.module.TextExp.name=Chinese document/instruction/tutorial/manual: 

voice.module.tip.import=Import the file that composes the voice data.<br>The file should be generated by eGPS.
voice.module.msg.import=Import process finished, please re-start the dialog.
voice.module.tip.export=Export the file that composes the voice data.<br>It can be reused again.
voice.module.tip.wrapline=Whether wrap the line.
voice.module.tip.dragfile= \ Drag your input file here.
voice.module.button.importAr=Execute script & Save
voice.module.title.inputArea=Direct input content or load from the file.
voice.module.title.bookmark=Bookmark operation

history.module.menu.feature=Major features
history.module.menu.history.detail=History details
history.module.dialog.title=History dialog

turnToHistory.module.button.tip=Show/Hide Adjust Panel
turnToHistory.module.search.name=Search:

### Software hint statements

Application.hint.intro.button=<html><FONT face="Arial, sans-serif" color="black" size="5">Left click to <br>browser the module,<br>double click or right click to <br>launch the module.</font></html>
Application.hint.itools.button=<html><FONT face="Arial, sans-serif" color="black" size="5">Click iTools menu<br>to see available <em>modules</em>.</html>
Application.hint.plugin.button=<html><FONT face="Arial, sans-serif" color="black" size="5">Click plug-ins menu<br>to see available <em>plug-ins</em>.</html>
Application.hint.gotit.button=<html><FONT face="Arial, sans-serif" color="black" size="5"><em>Got it!</em>.</html>
Application.hint.alreadyknown.button=<html><FONT face="Arial, sans-serif" color="black" size="5"><em>Already know, stop</em>.</html>
Application.hint.graphicPro.button=<html><FONT face="Arial, sans-serif" color="black" size="5">This the button to <br>toggle <em>Graphic properties panel</em>.</html>
Application.hint.buttomStatesBar=<html><FONT face="Arial, sans-serif" color="black" size="5">This is<br>the bottom status bar.<br>Each button is straightforward.</html>
Application.hint.info.button=<html><FONT face="Arial, sans-serif" color="black" size="5">This is information button.<br>Left is help, right is statics.<br>These are novel features.</html>
Application.hint.download.button=<html><FONT face="Arial, sans-serif" color="black" size="5">This is download button.<br>Current is not visible.<br>This button will be displayed<br>whenever there is an<br>incremental update</html>

web.environment.not.meet=The web environment is not meet. In order to better
download.web.failed=The download failed, please check your Internet.

output.success=Output successfully !

### Dialog text ###
dialog.error=Running Error
dialog.info=Information
dialog.import=Data import dialog
dialog.msg.finish=Successfully accomplish the action.
dialog.msg.export.finish=Successfully export the content to file.
dialog.msg.check.content=\nPlease check the input content.
dialog.save=Save as
dialog.open=Choose file

### Computational thread ###

thread.error.already=Sorry, there is already one task running.\tPlease wait or stop the running task.
thread.error.stepTooSmall=Sorry, as for the task with time could estimate, the input total step is less than 1.
thread.info.taskFinished=The computation task has already done for the module 


action.about.check.update=Check for updates
action.about.dialog.title="About dialog"

cancel.text=Cancel


voice.demo.comp.console=This console displays usage tips<br>and live output for quick <em>feedback</em>.
voice.demo.bookmark.display=The bookmark <em>records</em> of script.<br>Most node operations are supported.
voice.demo.input.area=The running script of the <em>module</em>.
voice.demo.example.bottom=This is the <em>compass button</em>,<br>click to see the examples provided by the module.
voice.demo.bookmark.name=The record <em>name</em> in the bookmark Tree.
voice.demo.record.button=Record instantly on the Tree,<br>useful to test different parameters.
voice.demo.linking.button=Autosave/Linked the record when<br><em>click the running button</em>.
voice.demo.run.button=The must important button,<br><em>click to run analysis</em>.
module.demo.handy.tool


common.save.error.title=Save Error

common.save.confirm.title=Save Confirm
common.save.confirm.msg=There are unsaved user activities in this module.\nConfirm to save it?

mainframe.close.confirm.title=Close confirmation
mainframe.close.confirm.msg=There are ongoing operations or unsaved user activities in this module.\nAre you sure you want to close it?
